# Generated by Django 4.2.7 on 2023-11-25 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacionesusuario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 18, 48, 23, tzinfo=datetime.timezone.utc)),
        ),
    ]
