# Generated by Django 4.2.7 on 2023-11-26 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_operaciones', '0002_alter_operacionesusuario_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallegasto',
            name='etiqueta',
        ),
        migrations.RemoveField(
            model_name='detalleingreso',
            name='etiqueta',
        ),
        migrations.AddField(
            model_name='operacionesusuario',
            name='etiqueta',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='operacionesusuario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 0, 1, 29, tzinfo=datetime.timezone.utc)),
        ),
    ]
