# Generated by Django 4.2.7 on 2023-11-26 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_operaciones', '0003_remove_detallegasto_etiqueta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacionesusuario',
            name='fecha',
        ),
        migrations.AddField(
            model_name='operacionesusuario',
            name='fecha_operacion',
            field=models.DateField(default=datetime.datetime(2023, 11, 26, 0, 25, 21, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='operacionesusuario',
            name='hora_operacion',
            field=models.TimeField(default=datetime.time(19, 25, 21)),
        ),
    ]
