# Generated by Django 4.2.7 on 2023-11-27 03:30

from django.db import migrations, models
import gestor_operaciones.utils


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_operaciones', '0007_alter_operacionesusuario_fecha_operacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacionesusuario',
            name='fecha_operacion',
            field=models.DateField(default=gestor_operaciones.utils.fecha_actual),
        ),
        migrations.AlterField(
            model_name='operacionesusuario',
            name='hora_operacion',
            field=models.TimeField(default=gestor_operaciones.utils.hora_actual),
        ),
    ]
