# Generated by Django 4.2.7 on 2023-12-02 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestor_cartera', '0002_initial'),
        ('gestor_operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyeccionesFinancieras',
            fields=[
                ('pf_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('etiqueta', models.CharField(max_length=50)),
                ('cantidad_proyeccion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_progreso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cu_id', models.ForeignKey(db_column='cu_id', on_delete=django.db.models.deletion.PROTECT, to='gestor_cartera.carterausuario')),
                ('to_id', models.ForeignKey(db_column='to_id', on_delete=django.db.models.deletion.PROTECT, to='gestor_operaciones.tipooperacion')),
            ],
            options={
                'db_table': 'proyecciones_financieras',
            },
        ),
        migrations.CreateModel(
            name='HistoricoProyeccionesFinancieras',
            fields=[
                ('hpf_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('etiqueta', models.CharField(max_length=50)),
                ('cantidad_proyeccion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_final', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cu_id', models.ForeignKey(db_column='op_id', on_delete=django.db.models.deletion.PROTECT, to='gestor_cartera.carterausuario')),
                ('to_id', models.ForeignKey(db_column='to_id', on_delete=django.db.models.deletion.PROTECT, to='gestor_operaciones.tipooperacion')),
            ],
            options={
                'db_table': 'historico_proyecciones_financieras',
            },
        ),
    ]
