# Generated by Django 4.2.7 on 2023-12-02 01:09

from django.db import migrations, models
import gestor_operaciones.utils


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_proyecciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoproyeccionesfinancieras',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historicoproyeccionesfinancieras',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='proyeccionesfinancieras',
            name='fecha_fin',
            field=models.DateField(default=gestor_operaciones.utils.adicion_fecha_actual),
        ),
        migrations.AddField(
            model_name='proyeccionesfinancieras',
            name='fecha_inicio',
            field=models.DateField(default=gestor_operaciones.utils.fecha_actual),
        ),
    ]
