# Generated by Django 4.2.7 on 2023-11-25 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteraUsuario',
            fields=[
                ('cu_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('divisa', models.CharField(max_length=3)),
                ('u_id', models.OneToOneField(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cartera_usuario',
            },
        ),
    ]
