# Generated by Django 4.2.7 on 2023-11-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarteraUsuario',
            fields=[
                ('cu_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('divisa', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'cartera_usuario',
            },
        ),
    ]
