# Generated by Django 4.2.7 on 2023-11-18 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
