# Generated by Django 4.2.7 on 2023-11-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='u_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
