# Generated by Django 4.2.7 on 2023-11-06 20:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteraUsuario',
            fields=[
                ('cu_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('divisa', models.CharField(max_length=3)),
                ('u_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriasGasto',
            fields=[
                ('cg_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_cg', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriasIngreso',
            fields=[
                ('ci_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_ci', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOperacion',
            fields=[
                ('to_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nom_to', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubcategoriasIngreso',
            fields=[
                ('sci_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_sci', models.CharField(max_length=20)),
                ('ci_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestor_finanzas.categoriasingreso')),
            ],
        ),
        migrations.CreateModel(
            name='SubcategoriasGasto',
            fields=[
                ('scg_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_scg', models.CharField(max_length=20)),
                ('cg_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestor_finanzas.categoriasgasto')),
            ],
        ),
        migrations.CreateModel(
            name='PlanesGasto',
            fields=[
                ('pg_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('etiqueta', models.CharField(max_length=30)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cg_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestor_finanzas.categoriasgasto')),
                ('cu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_finanzas.carterausuario')),
            ],
        ),
        migrations.CreateModel(
            name='OperacionesUsuarioProgramadas',
            fields=[
                ('op_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2023, 11, 6, 20, 9, 44, 992500, tzinfo=datetime.timezone.utc))),
                ('dia', models.TextField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')])),
                ('activo', models.BooleanField(default=True)),
                ('cu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_finanzas.carterausuario')),
                ('to_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestor_finanzas.tipooperacion')),
            ],
        ),
        migrations.CreateModel(
            name='OperacionesUsuario',
            fields=[
                ('o_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2023, 11, 6, 20, 9, 44, 991838, tzinfo=datetime.timezone.utc))),
                ('cu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_finanzas.carterausuario')),
                ('to_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestor_finanzas.tipooperacion')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoPlanesGasto',
            fields=[
                ('hpg_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('etiqueta', models.CharField(max_length=30)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cg_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestor_finanzas.categoriasgasto')),
                ('cu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_finanzas.carterausuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleIngresoProgramado',
            fields=[
                ('dip_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('etiqueta', models.CharField(max_length=30)),
                ('op_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gestor_finanzas.operacionesusuarioprogramadas')),
                ('sci_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestor_finanzas.subcategoriasingreso')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleIngreso',
            fields=[
                ('di_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('etiqueta', models.CharField(max_length=30)),
                ('o_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gestor_finanzas.operacionesusuario')),
                ('sci_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestor_finanzas.subcategoriasingreso')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleGastoProgramado',
            fields=[
                ('dgp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('etiqueta', models.CharField(max_length=30)),
                ('subsidiado', models.BooleanField(default=False)),
                ('o_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gestor_finanzas.operacionesusuarioprogramadas')),
                ('scg_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestor_finanzas.subcategoriasgasto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleGasto',
            fields=[
                ('dg_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('etiqueta', models.CharField(max_length=30)),
                ('subsidiado', models.BooleanField(default=False)),
                ('o_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gestor_finanzas.operacionesusuario')),
                ('scg_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestor_finanzas.subcategoriasgasto')),
            ],
        ),
    ]
