# Generated by Django 4.2.7 on 2023-11-06 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_finanzas', '0003_remove_detallegastoprogramado_o_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallegastoprogramado',
            name='op_id',
            field=models.OneToOneField(db_column='op_id', on_delete=django.db.models.deletion.PROTECT, to='gestor_finanzas.operacionesusuarioprogramadas'),
        ),
        migrations.AlterField(
            model_name='detalleingresoprogramado',
            name='op_id',
            field=models.OneToOneField(db_column='op_id', on_delete=django.db.models.deletion.PROTECT, to='gestor_finanzas.operacionesusuarioprogramadas'),
        ),
    ]
