# Generated by Django 4.2.7 on 2023-11-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_finanzas', '0004_alter_detallegastoprogramado_op_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carterausuario',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='operacionesusuario',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='operacionesusuarioprogramadas',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='planesgasto',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicoplanesgasto',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
