# Generated by Django 4.2.7 on 2023-11-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_finanzas', '0005_carterausuario_saldo_operacionesusuario_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriasgasto',
            name='cg_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='categoriasgasto',
            name='nom_cg',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='categoriasingreso',
            name='nom_ci',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='detallegasto',
            name='etiqueta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='detallegastoprogramado',
            name='etiqueta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='detalleingreso',
            name='etiqueta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='detalleingresoprogramado',
            name='etiqueta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicoplanesgasto',
            name='etiqueta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='planesgasto',
            name='etiqueta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategoriasgasto',
            name='nom_scg',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategoriasingreso',
            name='nom_sci',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tipooperacion',
            name='nom_to',
            field=models.CharField(max_length=30),
        ),
    ]
