# Generated by Django 4.2.7 on 2023-11-18 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_finanzas', '0006_alter_categoriasgasto_cg_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carterausuario',
            table='cartera_usuario',
        ),
        migrations.AlterModelTable(
            name='categoriasgasto',
            table='categorias_gasto',
        ),
        migrations.AlterModelTable(
            name='categoriasingreso',
            table='categorias_ingreso',
        ),
        migrations.AlterModelTable(
            name='detallegasto',
            table='detalle_gasto',
        ),
        migrations.AlterModelTable(
            name='detallegastoprogramado',
            table='detalle_gasto_programado',
        ),
        migrations.AlterModelTable(
            name='detalleingreso',
            table='detalle_ingreso',
        ),
        migrations.AlterModelTable(
            name='detalleingresoprogramado',
            table='detalle_ingreso_programado',
        ),
        migrations.AlterModelTable(
            name='historicoplanesgasto',
            table='historico_planes_gasto',
        ),
        migrations.AlterModelTable(
            name='operacionesusuario',
            table='operaciones_usuario',
        ),
        migrations.AlterModelTable(
            name='operacionesusuarioprogramadas',
            table='operaciones_usuario_programadas',
        ),
        migrations.AlterModelTable(
            name='planesgasto',
            table='planes_gasto',
        ),
        migrations.AlterModelTable(
            name='subcategoriasgasto',
            table='subcategorias_gasto',
        ),
        migrations.AlterModelTable(
            name='subcategoriasingreso',
            table='subcategorias_ingreso',
        ),
        migrations.AlterModelTable(
            name='tipooperacion',
            table='tipo_operacion',
        ),
    ]
