# Generated by Django 4.2.7 on 2023-11-19 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_finanzas', '0007_alter_carterausuario_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoProyeccionesFinancieras',
            fields=[
                ('hpf_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('etiqueta', models.CharField(max_length=50)),
                ('cantidad_proyeccion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_final', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cu_id', models.ForeignKey(db_column='op_id', on_delete=django.db.models.deletion.PROTECT, to='gestor_finanzas.carterausuario')),
                ('to_id', models.ForeignKey(db_column='to_id', on_delete=django.db.models.deletion.PROTECT, to='gestor_finanzas.tipooperacion')),
            ],
            options={
                'db_table': 'historico_proyecciones_financieras',
            },
        ),
        migrations.CreateModel(
            name='ProyeccionesFinancieras',
            fields=[
                ('pf_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('etiqueta', models.CharField(max_length=50)),
                ('cantidad_proyeccion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_progreso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cu_id', models.ForeignKey(db_column='op_id', on_delete=django.db.models.deletion.PROTECT, to='gestor_finanzas.carterausuario')),
                ('to_id', models.ForeignKey(db_column='to_id', on_delete=django.db.models.deletion.PROTECT, to='gestor_finanzas.tipooperacion')),
            ],
            options={
                'db_table': 'proyecciones_financieras',
            },
        ),
        migrations.RemoveField(
            model_name='planesgasto',
            name='cg_id',
        ),
        migrations.RemoveField(
            model_name='planesgasto',
            name='cu_id',
        ),
        migrations.RemoveField(
            model_name='detallegasto',
            name='subsidiado',
        ),
        migrations.DeleteModel(
            name='HistoricoPlanesGasto',
        ),
        migrations.DeleteModel(
            name='PlanesGasto',
        ),
    ]
