# Generated by Django 4.2.7 on 2023-11-20 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_finanzas', '0008_historicoproyeccionesfinancieras_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacionesusuarioprogramadas',
            name='dia',
        ),
    ]
