# Generated by Django 4.2.7 on 2023-11-21 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_finanzas', '0009_remove_operacionesusuarioprogramadas_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacionesusuario',
            name='to_id',
            field=models.ForeignKey(db_column='to_id', on_delete=django.db.models.deletion.PROTECT, related_name='tipo_operacion', to='gestor_finanzas.tipooperacion'),
        ),
    ]
