# Generated by Django 4.2.7 on 2023-11-21 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_finanzas', '0010_alter_operacionesusuario_to_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacionesusuario',
            name='to_id',
            field=models.ForeignKey(db_column='to_id', on_delete=django.db.models.deletion.PROTECT, to='gestor_finanzas.tipooperacion'),
        ),
    ]
