# Generated by Django 4.2.7 on 2023-11-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_finanzas', '0011_alter_operacionesusuario_to_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('d_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_dia', models.CharField(max_length=20)),
            ],
        ),
    ]
