# Generated by Django 4.2.7 on 2023-11-25 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_finanzas', '0012_diasemana'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diasemana',
            table='dia_semana',
        ),
    ]
