# Generated by Django 4.2.7 on 2023-11-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_finanzas', '0013_alter_diasemana_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacionesusuarioprogramadas',
            name='dias',
            field=models.ManyToManyField(to='gestor_finanzas.diasemana'),
        ),
    ]
