# Generated by Django 4.2.7 on 2023-11-25 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_finanzas', '0014_operacionesusuarioprogramadas_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacionesusuarioprogramadas',
            name='hora',
            field=models.TimeField(default=datetime.time(4, 48, 30, 504266)),
        ),
    ]
