# Generated by Django 4.2.7 on 2023-11-25 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_finanzas', '0015_operacionesusuarioprogramadas_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacionesusuario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 16, 27, 20, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='operacionesusuarioprogramadas',
            name='hora',
            field=models.TimeField(default=datetime.time(11, 27, 20)),
        ),
    ]
