# Generated by Django 4.2.7 on 2023-11-25 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_finanzas', '0019_alter_operacionesusuario_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacionesusuarioprogramadas',
            name='dias',
        ),
        migrations.RemoveField(
            model_name='operacionesusuarioprogramadas',
            name='hora',
        ),
        migrations.AlterField(
            model_name='operacionesusuario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 17, 11, 15, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='operacionesusuarioprogramadas',
            name='fecha',
            field=models.DateTimeField(default=datetime.time(12, 11, 15)),
        ),
        migrations.DeleteModel(
            name='DiaSemana',
        ),
    ]
