# Generated by Django 4.2.7 on 2023-11-25 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_finanzas', '0020_remove_operacionesusuarioprogramadas_dias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('d_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_dia', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='operacionesusuario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 17, 13, 2, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='operacionesusuarioprogramadas',
            name='fecha',
            field=models.DateTimeField(default=datetime.time(12, 13, 2)),
        ),
        migrations.AddField(
            model_name='operacionesusuarioprogramadas',
            name='dias',
            field=models.ManyToManyField(to='gestor_finanzas.diasemana'),
        ),
    ]
