# Generated by Django 4.2.7 on 2023-11-25 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_finanzas', '0023_alter_operacionesusuario_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacionesusuarioprogramadas',
            name='hora',
            field=models.TimeField(default=datetime.time(12, 39, 45)),
        ),
        migrations.AlterField(
            model_name='operacionesusuario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 17, 39, 45, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='operacionesusuarioprogramadas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 17, 39, 45, tzinfo=datetime.timezone.utc)),
        ),
    ]
