# Generated by Django 4.2.7 on 2023-11-25 18:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestor_cartera', '0001_initial'),
        ('gestor_operaciones', '0002_alter_operacionesusuario_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('d_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_dia', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'dia_semana',
            },
        ),
        migrations.CreateModel(
            name='OperacionesUsuarioProgramadas',
            fields=[
                ('op_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2023, 11, 25, 18, 48, 23, tzinfo=datetime.timezone.utc))),
                ('hora', models.TimeField(default=datetime.time(13, 48, 23))),
                ('activo', models.BooleanField(default=True)),
                ('cu_id', models.ForeignKey(db_column='cu_id', on_delete=django.db.models.deletion.PROTECT, to='gestor_cartera.carterausuario')),
                ('dias', models.ManyToManyField(to='gestor_operaciones_programadas.diasemana')),
                ('to_id', models.ForeignKey(db_column='to_id', on_delete=django.db.models.deletion.PROTECT, to='gestor_operaciones.tipooperacion')),
            ],
            options={
                'db_table': 'operaciones_usuario_programadas',
            },
        ),
        migrations.CreateModel(
            name='DetalleIngresoProgramado',
            fields=[
                ('dip_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('etiqueta', models.CharField(max_length=50)),
                ('op_id', models.OneToOneField(db_column='op_id', on_delete=django.db.models.deletion.PROTECT, to='gestor_operaciones_programadas.operacionesusuarioprogramadas')),
                ('sci_id', models.ForeignKey(db_column='sci_id', on_delete=django.db.models.deletion.PROTECT, to='gestor_operaciones.subcategoriasingreso')),
            ],
            options={
                'db_table': 'detalle_ingreso_programado',
            },
        ),
        migrations.CreateModel(
            name='DetalleGastoProgramado',
            fields=[
                ('dgp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('etiqueta', models.CharField(max_length=50)),
                ('subsidiado', models.BooleanField(default=False)),
                ('op_id', models.OneToOneField(db_column='op_id', on_delete=django.db.models.deletion.PROTECT, to='gestor_operaciones_programadas.operacionesusuarioprogramadas')),
                ('scg_id', models.ForeignKey(db_column='scg_id', on_delete=django.db.models.deletion.PROTECT, to='gestor_operaciones.subcategoriasgasto')),
            ],
            options={
                'db_table': 'detalle_gasto_programado',
            },
        ),
    ]
