# Generated by Django 4.2.7 on 2023-11-25 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_operaciones_programadas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallegastoprogramado',
            name='subsidiado',
        ),
        migrations.AlterField(
            model_name='operacionesusuarioprogramadas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 18, 49, 43, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='operacionesusuarioprogramadas',
            name='hora',
            field=models.TimeField(default=datetime.time(13, 49, 43)),
        ),
    ]
