# Generated by Django 4.2.7 on 2023-12-02 00:43

from django.db import migrations, models
import gestor_operaciones.utils


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_operaciones_programadas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacionesusuarioprogramadas',
            name='hora_programada_hasta',
            field=models.TimeField(default=gestor_operaciones.utils.adicion_hora_actual),
        ),
    ]
