# Generated by Django 4.2.7 on 2023-11-26 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_operaciones_programadas', '0003_remove_detallegastoprogramado_etiqueta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacionesusuarioprogramadas',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='operacionesusuarioprogramadas',
            name='hora',
        ),
        migrations.AddField(
            model_name='operacionesusuarioprogramadas',
            name='fecha_operacion',
            field=models.DateField(default=datetime.datetime(2023, 11, 26, 0, 35, 39, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='operacionesusuarioprogramadas',
            name='hora_generacion',
            field=models.TimeField(default=datetime.time(19, 35, 39)),
        ),
        migrations.AddField(
            model_name='operacionesusuarioprogramadas',
            name='hora_operacion',
            field=models.TimeField(default=datetime.time(19, 35, 39)),
        ),
    ]
