# Generated by Django 4.2.7 on 2023-11-26 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_operaciones_programadas', '0004_remove_operacionesusuarioprogramadas_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacionesusuarioprogramadas',
            name='hora_generacion',
        ),
        migrations.AddField(
            model_name='operacionesusuarioprogramadas',
            name='hora_programada',
            field=models.TimeField(default=datetime.time(23, 24, 9)),
        ),
        migrations.AlterField(
            model_name='operacionesusuarioprogramadas',
            name='fecha_operacion',
            field=models.DateField(default=datetime.datetime(2023, 11, 26, 4, 24, 9, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='operacionesusuarioprogramadas',
            name='hora_operacion',
            field=models.TimeField(default=datetime.time(23, 24, 9)),
        ),
    ]
