# Generated by Django 4.2.7 on 2023-11-26 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_operaciones_programadas', '0005_remove_operacionesusuarioprogramadas_hora_generacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacionesusuarioprogramadas',
            name='hora_programada',
        ),
        migrations.AddField(
            model_name='operacionesusuarioprogramadas',
            name='hora_programada_desde',
            field=models.TimeField(default=datetime.time(13, 53, 27)),
        ),
        migrations.AddField(
            model_name='operacionesusuarioprogramadas',
            name='hora_programada_hasta',
            field=models.TimeField(default=datetime.time(19, 53, 27)),
        ),
        migrations.AlterField(
            model_name='operacionesusuarioprogramadas',
            name='fecha_operacion',
            field=models.DateField(default=datetime.datetime(2023, 11, 26, 18, 53, 27, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='operacionesusuarioprogramadas',
            name='hora_operacion',
            field=models.TimeField(default=datetime.time(13, 53, 27)),
        ),
    ]
