# Generated by Django 4.2.7 on 2023-11-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_operaciones_programadas', '0007_alter_operacionesusuarioprogramadas_fecha_operacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacionesusuarioprogramadas',
            name='hora_programada_hasta',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
